name: build and publish release
on:
  push:
    tags:
      - v**
  # 手动触发工作流
  workflow_dispatch:

env:
  GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
  GPG_SECRET_KEY: ${{ secrets.GPG_PRI_KEY }}
  GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.OSS_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.OSS_PASSWORD }}
  RELEASE: true
  CI: true
  IS_CI: true
  GRADLE_OPTS: "-Dfile.encoding=UTF-8"
  GRADLE_JAVA_VERSION: 11
  GRADLE_JAVA_DISTRIBUTION: 'zulu'
  GRADLE_VERSION: 8.8

jobs:
  test:
    name: Build test
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.GRADLE_JAVA_DISTRIBUTION }}
          java-version: ${{ env.GRADLE_JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - run: gradle assemble allTests -s

  publish:
    name: Publish
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      # Setup java
      # https://github.com/marketplace/actions/setup-java-jdk
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.GRADLE_JAVA_DISTRIBUTION }}
          java-version: ${{ env.GRADLE_JAVA_VERSION }}

      - name: Test and publish to sonatype
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments:
            publishToSonatype
            closeAndReleaseStagingRepositories
            -s
            --warning-mode all
            -x test
            --build-cache
            -Porg.gradle.jvmargs="-XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8"
            -Porg.gradle.daemon=false
        env:
          PLUGIN_AUTO: true

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [ publish ]
    permissions:
      contents: write
    steps:
      #      - uses: actions/checkout@v4
      #      - uses: actions/setup-java@v4
      #        with:
      #          distribution:
      #          java-version: 8
      #
      #      - name: Create changelog
      #        uses: gradle/actions/setup-gradle@v3
      #        with:
      #          gradle-version: 8.5
      #          arguments: createChangelog

      # https://github.com/softprops/action-gh-release
      # Create gitHub release
      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.FORTE_TOKEN }}
          draft: true
          # body_path: .changelog/${{ github.ref_name }}.md
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, 'preview') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
